# Generated by Django 6.0.4 on 2026-04-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
